baseURL: "https://h5law.com/"
title: h5law
paginate: 5
theme: "PaperMod"
languageCode: "en-gb"

enablenableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: h5law
  description: "h5law's personal site"
  keywords: [Blog, Portfolio]
  author: h5law
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/apple-touch-icon.png"
    safari_pinned_tab: "/img/favicon.ico"

  label:
    text: "h5law"
    icon: "/img/logo.png"
    iconHeight: 35

  # home-info mode
  # homeInfoParams:
  #   enabled: false
  #   Title: "Hey \U0001F44B"
  #   Subtitle: "Welcome to my blog!"

  profileMode:
    enabled: true
    title: "h5law"
    subtitle: "Welcome To My Site 👋"
    content: >
       This is intended to be a collection of articles, write ups on projects and quick thoughts. For a **tl;dr** on me:
    tldr: >
       Protocol Developer 👨🏼‍💻

  
       Notorious Industry Plant 🪴
    imageUrl: "/img/logo.png"
    imageTitle: "h5law - Protocol Developer" # optional
    imageWidth: 128
    imageHeight: 128
    buttons:
      - name: Posts
        url: "/posts"
      - name: Archives
        url: "/archives"

  socialIcons:
    - name: twitter
      url: "https://x.com/h5law"
    - name: github
      url: "https://github.com/h5law"
    - name: rss
      url: "https://h5law.com/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  categories: categories
  tag: tags

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archives 
      name: Archives 
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 40

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: dracula
